[Interface]
PrivateKey = 2Ed/k2suUBmk6cJMwdzef6mdtU2s7h4Ng4XetxW2Yk0=
Address = 10.99.0.11/24
DNS = 1.1.1.1

[Peer]
PublicKey = mb/+e+mK8rkLv1C1NvWiH9ef4mETZkXKHOh+Ga3xois=
Endpoint = 47.119.136.200:51820
AllowedIPs = 10.99.0.0/24
PersistentKeepalive = 25
