[Interface]
PrivateKey = MD2F9yXMX5Np2Xtd9KJOMGrZsanjlnYW43jbFkXeZXg=
Address = 10.99.0.12/24
DNS = 1.1.1.1

[Peer]
PublicKey = mb/+e+mK8rkLv1C1NvWiH9ef4mETZkXKHOh+Ga3xois=
Endpoint = 47.119.136.200:51820
AllowedIPs = 10.99.0.0/24
PersistentKeepalive = 25
